export {
  resolveProjectRoot,
  computeProjectId,
  getCacheDir,
  getPaths,
  readRegistry,
  writeRegistry,
  healthCheck,
  tryAcquireLock,
  releaseLock,
  randomToken,
  getDaemonEntryPath,
  ensureDaemonRunning,
  sleep,
  // Global daemon registry
  getGlobalIndexPath,
  readGlobalIndex,
  writeGlobalIndex,
  registerDaemonGlobally,
  unregisterDaemonGlobally,
  cleanupGlobalIndex,
  discoverAllDaemons,
  // Types
  type DaemonRegistry,
  type DaemonPaths,
  type EnsureDaemonOptions,
  type ActiveDaemonEntry,
  type ActiveDaemonsIndex,
} from "./discovery.js";

export {
  // Message type constants
  HELLO_TEST,
  HELLO_ACK,
  BATCH_MOCK_REQUEST,
  BATCH_MOCK_RESULT,
  HEARTBEAT,
  HEARTBEAT_ACK,
  // RPC method names
  RPC_GET_STATUS,
  RPC_LIST_RUNS,
  RPC_CLAIM_NEXT_BATCH,
  RPC_PROVIDE_BATCH,
  RPC_RELEASE_BATCH,
  RPC_GET_BATCH,
  // Error codes
  RPC_ERROR_PARSE,
  RPC_ERROR_INVALID_REQUEST,
  RPC_ERROR_METHOD_NOT_FOUND,
  RPC_ERROR_INVALID_PARAMS,
  RPC_ERROR_INTERNAL,
  RPC_ERROR_NOT_FOUND,
  RPC_ERROR_UNAUTHORIZED,
  RPC_ERROR_CONFLICT,
  RPC_ERROR_EXPIRED,
  // Validation functions
  isHelloTestMessage,
  isBatchMockRequestMessage,
  isHeartbeatMessage,
  isJsonRpcRequest,
  // Types
  type HelloTestMessage,
  type HelloAckMessage,
  type BatchMockRequestMessage,
  type BatchMockResultMessage,
  type HeartbeatMessage,
  type HeartbeatAckMessage,
  type TestChannelIncomingMessage,
  type TestChannelOutgoingMessage,
  type JsonRpcRequest,
  type JsonRpcResponse,
  type JsonRpcError,
  type ClaimNextBatchParams,
  type ClaimNextBatchResult,
  type ProvideBatchParams,
  type ProvideBatchResult,
  type ReleaseBatchParams,
  type GetBatchParams,
  type GetStatusResult,
  type ListRunsResult,
  type RunInfo,
  type GetBatchResult,
  type BatchStatus,
  type RunRecord,
  type BatchRecord,
} from "./protocol.js";
